source "https://rubygems.org"
ruby "3.2.3"

gem "rails", "~> 7.1.5"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.8"
gem "rack-cors", "~> 2.0"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri]
end
